#!/usr/bin/env bash
#
# Install and configure nginx to listen on port 80
#

config="\
server {
	listen 80;
	location / {
		root /usr/share/nginx/html;
		index index.html;
		add_header X-Served-By \$hostname;
	}

	location /redirect_me {
		return 301 https://www.holbertonschool.com;
	}

	error_page 404 /youputaspace.html;

	location /youputaspace.html {
		root /usr/share/nginx/html;
		internal;
	}
}
"

function bye() {
	echo "$2"
	exit "$1"
}

apt-get install -y nginx > /dev/null 2>&1
service nginx stop > /dev/null 2>&1
rm -rf /etc/nginx/sites-enabled/* /usr/share/nginx/html/* > /dev/null 2>&1
echo "$config" > /etc/nginx/sites-enabled/holberton
echo 'Holberton School' > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/youputaspace.html
service nginx start
bye 0 'nginx installed and configured'
