name             'holberton-wrapper'
maintainer       'Rick Harris'
maintainer_email 'rick.harris@holbertonschool.com'
license          'All rights reserved'
description      'Installs/Configures holberton-wrapper'
long_description 'Installs/Configures holberton-wrapper'
version          '0.1.0'
