#!/usr/bin/env bash
# Script that outputs 'To infinity and beyond' and other messages
echo $$ > /var/run/holbertonscript.pid
function cleanup {
	rm -f /var/run/holbertonscript.pid
	exit
}
trap "echo I hate the kill command; cleanup" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "cleanup" SIGQUIT
while :
do
	echo To infinity and beyond
	sleep 2
done
